### PR TITLE
Created a parameter for returning error code

### PR DESCRIPTION
**Pull request by Glamhoth**

### CODE REVIEW

**Comment by regebro** [comment]
Thanks, this looks good, but I think `--check` should suppress the output, since it's a check if there is a difference you don't want to deal with that output.

I also wonder if it doesn't make more sense to always return 1 when there is a difference, even without the `--check` parameter.

**Comment by Glamhoth** [comment]
> I also wonder if it doesn't make more sense to always return 1 when there is a difference
I thought about it too, but I didn't want to change default behavior. If someone is using xmldiff in their scrips/pipeline then such change could break them.

> but I think --check should suppress the output, since it's a check if there is a difference you don't want to deal with that output.
Actually printing output when there is a difference is quite useful (and diff does it that way). For example in my case, `xmldiff` is used in integration tests which are run on the CI. Output is handy to quickly see why given test failed. Suppressing output could be implemented by `-q / --quiet` parameter maybe?

**Comment by regebro** [comment]
OK, let's do it that way.

**Comment by Glamhoth** [comment]
@regebro conflicts are resolved

**Pull request closed without merging**
